settings:
  title: 'Liberate City Status'
  url: 'https://status.gtarphk.com' # used for Slack messages
  logo: 'https://raw.githubusercontent.com/RyanL-29/lbcity/main/artworks-000435425847-da5cv7-t500x500.png' # image in ./public/ folder
  daysInHistogram: 100 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有系統均正常運作中'
  notAllmonitorsOperational: '有部分系統出現問題'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Error'
  monitorLabelNoData: '沒有數據'
  dayInHistogramNoData: '沒有數據'
  dayInHistogramOperational: '正常'
  dayInHistogramNotOperational: ' 錯誤' # xx incident(s) recorded

monitors:
  - id: mainser # unique identifier
    name: 核心伺服器
    description: '伺服器運作狀態 (不是遊戲程序狀態)' # default=empty
    url: 'http://gtarphk.com:8080/dashboard/faq.html' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false

  - id: gameser
    name: FXServer
    description: '遊戲程序狀態'
    url: 'https://cfx.re/join/2l3ro7'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    
  - id: fivemm
    name: FiveM 伺服器
    description: 'Cfx.re 狀態'
    url: 'https://runtime.fivem.net/'
    method: GET
    expectStatus: 403
    followRedirect: true # should fetch follow redirects, default=false
    
  - id: fivemauth
    name: FiveM 驗證伺服器
    description: '負責對玩家及伺服器進行驗證'
    url: 'https://keymaster.fivem.net/'
    method: GET
    expectStatus: 403
    followRedirect: true # should fetch follow redirects, default=false
